%YAML:1.0
#cautious: NO TABS!!!!!!!
CAMERA_NODE:{
    ENABLE: 0,
    ID: 0,
    WIDTH: 1280,
    HEIGHT: 720,
    CAMERA_INTRINSIC_XML: "camera_intrinsic.xml"}
LOG_NODE:{
    ENABLE: 1,
    LOG_FILE_PATH: "../log/",
    WIDTH: 1280,
    HEIGHT: 720}
SOCKET_SEND_NODE:{
    ENABLE: 1,
    HOST: "127.0.0.1",
    PORT: 8080,
    IMG_MSG_FREQ: 30,
    IMG_MSG_RESIZE: 0.1,
    IMG_MSG_QUALITY: 30}
SOCKET_RECV_NODE:{
    ENABLE: 1,
    HOST: "127.0.0.1",
    PORT: 8080}
CONTROL_NODE:{
    ENABLE: 1,
    URL: "serial:///dev/ttyUSB0:115200",
    TAKEOFF_ALTITUDE: 4.0}
