%YAML:1.0
#cautious: NO TABS!!!!!!!
CAMERA_NODE:{
    ENABLE: 1,
    ID: 1,
    WIDTH: 1280,
    HEIGHT: 720,
    CAMERA_INTRINSIC_XML: "../config/camera_intrinsic.xml"}
LOG_NODE:{
    ENABLE: 1,
    LOG_FILE_PATH: "../log/",
    WIDTH: 1280,
    HEIGHT: 720}
SOCKET_SEND_NODE:{
    ENABLE: 1,
    HOST: "127.0.0.1",
    PORT: 8080,
    GRAY_IMG: 1,
    IMG_MSG_RESIZE: 0.2,
    IMG_MSG_QUALITY: 30}
SOCKET_RECV_NODE:{
    ENABLE: 1,
    HOST: "127.0.0.1",
    PORT: 8080}
CONTROL_NODE:{
    ENABLE: 1,
    Kp_z: 0.2,
    Ki_z: 0.001,
    Kd_z: 0.1,
    URL: "serial:///dev/ttyUSB0:115200",
    TAKEOFF_ALTITUDE: 4.0}
