%YAML:1.0
#cautious: NO TABS!!!!!!!
CAMERA_NODE:{
    ENABLE: 1,
    ID: 0,
    WIDTH: 1280,
    HEIGHT: 800,
    CAMERA_INTRINSIC_XML: "../config/camera_intrinsic.xml"}
SOCKET_SEND_NODE:{
    ENABLE: 1,
    HOST: "192.168.43.230",
    PORT: 8080,
    GRAY_IMG: 0,
    IMG_MSG_RESIZE: 0.1,
    IMG_MSG_QUALITY: 30}
SOCKET_RECV_NODE:{
    ENABLE: 1,
    HOST: "192.168.43.230",
    PORT: 8080}
CONTROL_NODE:{
    ENABLE: 1,
    URL: "serial:///dev/ttyS0:115200",
    Kp_z: 1.0,
    Ki_z: 0.001,
    Kd_z: 0.3,
    Kp_x: 0.1,
    Ki_x: 0.0,
    Kd_x: 0.03,
    Kp_y: 0.2,
    Ki_y: 0.0,
    Kd_y: 0.08,
    TAKEOFF_ALTITUDE: 4.0}
