%YAML:1.0
#cautious: NO TABS!!!!!!!
CAMERA_NODE:{
    ENABLE: 1,
    ID: 0,
    WIDTH: 1280,
    HEIGHT: 800,
    CAMERA_INTRINSIC_XML: "camera_intrinsic.xml"}
SOCKET_SEND_NODE:{
    ENABLE: 1,
    HOST: "192.168.11.27",
    PORT: 8080,
    GRAY_IMG: 1,
    IMG_MSG_RESIZE: 0.1,
    IMG_MSG_QUALITY: 30}
SOCKET_RECV_NODE:{
    ENABLE: 1,
    HOST: "192.168.11.27",
    PORT: 8080}
CONTROL_NODE:{
    ENABLE: 1,
    URL: "serial:///dev/ttyS0:115200",
    Kp_z: 1.6,
    Ki_z: 0.001,
    Kd_z: 0.5,
    TAKEOFF_ALTITUDE: 4.0}
